# Always validate the PR title, and ignore the commits
titleOnly: true

types:
  - chore               # An internal change this is not observable by users.
  - enhancement         # Any user observable enhancement to an existing feature.
  - feat                # Any user observable new feature, such as a new platform, source, transform, or sink.
  - fix                 # Any user observable bug fix.
  - docs                # A documentation change.
  - revert              # A revert of a previous change.
  - ci                  # A CI enhancement
