export * from './DownloadSection/DownloadSection';
export * from './SeeMoreSection/SeeMoreSection';
export * from './SeeMoreSection/model';
export * from './about-section/AboutAcordion';
export * from './earthquakes-map-section/EarthquakesMapSection';
export { default as HomeHeroSection } from './home-hero-section/HomeHeroSection';
export * from './legal-notice-section/LegalNoticeSection';
export * from './legal-notice-section/content';
export * from './ritcher-scale-section/RitcherScaleSection';
export * from './earthquakes-section/EarthquakesSection';
